(* ::Package:: *)

SetOptions[$FrontEnd,
NotebookBrowseDirectory->"",
AutoOpenPalettes->{},
AutoOpenPaclets->{},
DefaultStyleDefinitions->"CMU Article.nb",
ConversionOptions->{"ExportOptions"->{}},
ExportAutoReplacements->{"\[Rule]" -> "->", "\[RuleDelayed]" -> ":>", "\[LessEqual]" -> "<=", "\[GreaterEqual]" -> ">=", "\[NotEqual]" -> "!=", "\[Equal]" -> "==", "\[LongEqual]" -> "==", "\[LineSeparator]" -> "\n", "\[ParagraphSeparator]" -> "\n", "\[Hyphen]" -> "-", "\[LeftDoubleBracket]" -> "[[", "\[RightDoubleBracket]" -> "]]", "\[LeftSkeleton]" -> "<<", "\[RightSkeleton]" -> ">>", "" -> " ", "\[VeryThinSpace]" -> " ", "\[Times]" -> "*", "\[Divide]" -> "/", "\[ExponentialE]" -> "E", "\[ImaginaryI]" -> "I", "\[NoBreak]" -> "", "\[OpenCurlyQuote]" -> "'", "\[CloseCurlyQuote]" -> "'", "\[OpenCurlyDoubleQuote]" -> "\"", "\[CloseCurlyDoubleQuote]" -> "\""},
Language->"English",
"DisplayImagePixels"->"Automatic",
Default2DTool->"Select",
Default3DTool->"RotateView",
PrivateFrontEndOptions->{"LicensesAgreed"->{"11.0"}},
VersionsLaunched->{"8.0.0", "9.0.0", "10.0.0", "10.4.0", "11.0.0", "11.1.1", "11.3.0", "12.0.0"},
NotebooksMenu->{},
PalettesMenuSettings->{"SpecialCharacters.nb" -> {WindowMargins -> {{Automatic, 0}, {Automatic, 150}}, TaggingRules -> {"WholeCellGroupOpener" -> True, "LargerText" -> True, "MyBookmarks" -> {"/Users/faisal/Files/iOS/WolframCalculator/Docs/PredictionsMap.nb", "/Users/faisal/Files/iOS/WolframCalculator/resource/AddOns/Autoload/WolframCalculator/WolframCalculatorDebug.m", "/Users/faisal/Files/HEAD/Mathematica/FrontEnd/SystemFiles/FrontEnd/TextResources/GetFEKernelInit.tr", "/Users/faisal/Files/HEAD/Mathematica/FrontEnd/Source/NonC/"}, "lettersorsymbols" -> 2, "letterpage" -> 3, "symbolpage" -> 3}, Magnification -> 1}, "ChartElementSchemes.nb" -> {TaggingRules -> {"chartGroup" -> "Statistical", "curSel" -> {{"Histogram"}, "Rectangle"}, "showChartType" -> True, "showChartElems" -> True, "showManips" -> True, "showControls" -> True}}, "ColorSchemes.nb" -> {TaggingRules -> {"DocuToolsSettingsInternal" -> {"$ApplicationName" -> "Mathematica", "$LinkBase" -> "Mathematica", "$ApplicationDirectory" -> "/Users/brettc/Source/Head/Mathematica/", "$DocumentationDirectory" -> "/Users/brettc/Source/Head/Mathematica/Documentation/English/", "$UseNewPageDialog" -> "False"}, "GradientsOpener" -> True, "GradientsScroll" -> 42, "GradientsSelection" -> 43, "PhysicalOpener" -> False, "PhysicalScroll" -> 1, "PhysicalSelection" -> 1, "NamedOpener" -> False, "NamedMenu" -> 1, "IndexedOpener" -> False, "IndexedScroll" -> 109, "IndexedSelection" -> 1}}},
FontSubstitutions->{"CMU" -> "CMU Serif", "LaTeX" -> "CMU Serif", "Article" -> "CMU Serif", "Serif" -> "CMU Serif", "Sans" -> "CMU Sans Serif", "Sans Serif" -> "CMU Sans Serif", "Extra" -> "CMU Serif Extra", "Serif Extra" -> "CMU Serif Extra", "Demi" -> "CMU Sans Serif Demi Condensed", "Letter" -> "CMU Concrete", "Concrete" -> "CMU Concrete", "Bright" -> "CMU Bright", "Classical" -> "CMU Classical Serif", "Code" -> "CMU Typewriter Text", "Typewriter" -> "CMU Typewriter Text", "Helv" -> "Helvetica", "Arial" -> "Helvetica", "Times New Roman" -> "Times", "Courier New" -> "Courier", "Lucidabright" -> "Times", "Charter" -> "Helvetica", "Lucidatypewriter" -> "Courier", "Fixed" -> "Monaco", "AGaramond" -> "Times", "Avant Garde" -> "Helvetica", "Bodoni" -> "Times", "Bookman" -> "Times", "Caslon 3 Roman" -> "Times", "Caslon 540 Roman" -> "Times", "Century Old Style" -> "Times", "Chicago" -> "Helvetica", "Dom Casual" -> "Helvetica", "Futura" -> "Helvetica", "Futura Book" -> "Helvetica", "Futura Condensed" -> "Helvetica", "C Futura Condensed" -> "Helvetica", "Futura Light" -> "Helvetica", "L Futura Light" -> "Helvetica", "Galliard" -> "Times", "Garamond" -> "Times", "Geneva" -> "Helvetica", "GillSans" -> "Gill Sans", "Gill Sans" -> "Helvetica", "Goudy" -> "Times", "Helvetica Condensed" -> "Helvetica", "C Helvetica Condensed" -> "Helvetica", "Helvetica Light" -> "Helvetica", "L Helvetica Light" -> "Helvetica", "Helvetica Narrow" -> "Helvetica", "N Helvetica Narrow" -> "Helvetica", "Melior" -> "Times", "Meridien" -> "Times", "Mishawaka" -> "Helvetica", "Monaco" -> "Helvetica", "Myriad Pro" -> "Lucida Grande", "New Baskerville" -> "Times", "New Century Schlbk" -> "Times", "New York" -> "Times", "Optima" -> "Helvetica", "Palatino" -> "Times", "Palatino Linotype" -> "Palatino", "Prestige Elite" -> "Times", "Sabon" -> "Times", "Tekton" -> "Helvetica", "Trump Mediaeval" -> "Times", "Univers 45 Light" -> "Helvetica", "L Univers 45 Light" -> "Helvetica", "Univers 47 CondensedLight" -> "Helvetica", "CL Univers 47 CondensedLight" -> "Helvetica", "Univers 55" -> "Helvetica", "Univers 57 Condensed" -> "Helvetica", "C Univers 57 Condensed" -> "Helvetica", "Zapf Chancery" -> "Times", "Abadi MT Condensed Light" -> "Helvetica", "Algerian" -> "Times", "Arial Black" -> "Helvetica", "Arial Narrow" -> "Helvetica", "Arial Rounded MT Bold" -> "Helvetica", "Billboard" -> "Helvetica", "Book Antiqua" -> "Times", "Bookman Old Style" -> "Times", "Braggadocio" -> "Helvetica", "Britannic Bold" -> "Helvetica", "Brush Script MT" -> "Helvetica", "Calisto MT" -> "Helvetica", "Gill" -> "Trebuchet MS", "Trebuchet MS" -> "Helvetica", "Helvetica Neue" -> "Helvetica", "Baskerville" -> "Georgia", "Cochin" -> "Constantia", "Calibri" -> "Arial", "Cambria" -> "Times New Roman", "Candara" -> "Trebuchet MS", "Consolas" -> "Menlo", "Constantia" -> "Palatino", "Corbel" -> "Lucida Grande", "Century Gothic" -> "Helvetica", "Century Schoolbook" -> "Times", "Colonna MT" -> "Times", "Comic Sans MS" -> "Helvetica", "Desdemona" -> "Helvetica", "Excalibur Logotype" -> "Helvetica", "Excalibur Monospace" -> "Courier", "Excalibur Script" -> "Times", "Fixedsys" -> "Helvetica", "Footlight MT Light" -> "Times", "Georgia" -> "Times", "Haettenschweiler" -> "Helvetica", "Impact" -> "Helvetica", "Kino MT" -> "Helvetica", "Kool" -> "Helvetica", "Lucida Console" -> "Monaco", "Lucida Grande" -> "Tahoma", "Lucida Sans" -> "Helvetica", "Matura MT Script Capitals" -> "Times", "Modern" -> "Helvetica", "MS LineDraw" -> "Courier", "MS Sans Serif" -> "Helvetica", "MS Serif" -> "Times", "News Gothic MT" -> "Helvetica", "Playbill" -> "Helvetica", "Small Fonts" -> "Helvetica", "System" -> "Helvetica", "Tahoma" -> "Helvetica", "Verdana" -> "Helvetica", "Wide Latin" -> "Times", "Wingdings" -> "Times", "Gothic" -> "Helvetica", "New century schoolbook" -> "Times", "Swiss721bt" -> "Helvetica", "Terminal" -> "Courier", "Utopia" -> "Times", "Frutiger LT Std 55 Roman" -> "Helvetica", "FrutigerLTStd-Light" -> "Helvetica", "Janson Text LT Std" -> "Times", "WriCMTT-Base" -> "Courier", "Bitstream Vera Sans" -> "Helvetica", "Bitstream Vera Sans Mono" -> "Menlo", "DejaVu Sans Mono" -> "Menlo", "Lato" -> "Gill Sans"},
PreferencesSettings->{"Page"->"Interface"},
FindSettings->{"FindBoxes":>"",
"FindHistory":>{},
"FindString"->"",
"IgnoreCase"->False,
"ReplaceBoxes"->"",
"ReplaceHistory":>{},
"SearchType"->LiteralSearch,
"WindowMargins"->{{460, 456}, {319, 309}},
"Wraparound"->True},
ColorSelectorSettings->{"Color"->RGBColor[0., 0., 0.]},
GridCreationSettings->{"Columns"->3,
"DiagonalFill"->False,
"DiagonalFillText"->"1",
"DrawColumnLines"->False,
"DrawFrame"->False,
"DrawRowLines"->False,
"Fill"->False,
"FillText"->"0",
"Rows"->5,
"Type"->"PlainGridBox"},
OptionInspectorSettings->{"Scope"->"Global",
"ViewAs"->"Text",
"WindowMargins"->{{Automatic, 79}, {Automatic, 0}},
"WindowSize"->{925, 587}},
ErrorsDialogSettings->{"WindowMargins"->{{69, Automatic}, {42, Automatic}}},
StyleNameDialogSettings->{"Style"->"SmallText"},
HelpViewerSettings->{"WindowMargins"->{{Automatic, 28}, {Automatic, 45}},
"WindowSize"->{750, 500}},
WolframCloudSettings->{"ActivityMonitorWindowMargins"->{{Automatic, 0}, {Automatic, 0}},
"ActivityMonitorWindowSize"->{500, 250},
"OpenDialogWindowMargins"->Automatic,
"OpenDialogWindowSize"->{500, 600},
"SaveDialogWindowMargins"->Automatic,
"SaveDialogWindowSize"->{500, 600}},
NotebookSecurityOptions->{"TrustedPath"->{FrontEnd`FileName[{FrontEnd`$ApplicationDocumentsDirectory}], FrontEnd`FileName[{$InstallationDirectory}], FrontEnd`FileName[{$BaseDirectory}], FrontEnd`FileName[{$UserBaseDirectory}], "/Users/everett/Dropbox/Mathematica"}},
PrivateFrontEndOptions->{"DialogSettings"->{"Login" -> {"RememberMe" -> True}, "WelcomeScreen" -> {"ShowRecentFilesContextMenu" -> False}, "Preferences" -> {"SubTabs" -> {"Appearance" -> "Graphics", "SyntaxColoring" -> "Other", "Numbers" -> "Formatting", "Internet" -> "AutoUpdate", "Mail" -> "IncomingMail"}}},
"InterfaceSettings"->{"MessageStack" -> {"ImageSize" -> {600, 300}}},
"ShowAtStartup"->"NewDocument",
"WolframAlphaSettings"->{"Autoload" -> True, "BaseURL" -> "Automatic", "Asynchronous" -> True, "Interactive" -> True, "Reinterpret" -> True, "Recalculate" -> True, "MathematicaFormsFormatType" -> "MostlyInputForm", "ExtrusionClickClose" -> False, "ExtrusionClickEvaluate" -> False, "SendMathematicaSessionInfo" -> Automatic, "AppID" -> Automatic}},
MarkerLineThickness->1,
BlinkingCellInsertionPoint->False,
PrintingOptions->{"EmbedExternalFonts"->False,
"EmbedStandardPostScriptFonts"->False,
"OpacityRenderingMethod"->Automatic,
"RasterizationResolution"->"TargetDevice",
"VertexColorRenderingMethod"->"RasterizeFeatures"},
PrivateNotebookOptions->{"VersionedStylesheet"->{"Default.nb"[8.] -> False}},
PrivateCellOptions->{"EvaluationUnmatchedStyle"->None},
TaggingRules->{ScrollPosition -> {0., 120.}},
InputAliases->{"up" -> "\[UpArrow]", "dn" -> "\[DownArrow]", "->" -> "\[RightArrow]", "<-" -> "\[LeftArrow]", "<<" -> "\[LessLess]", ">>" -> "\[GreaterGreater]", "/" -> "\[Checkmark]", "ket" -> TemplateBox[{"\[Placeholder]"}, "Ket", DisplayFunction -> (RowBox[{"\[LeftBracketingBar]", #, "\[RightAngleBracket]"}]& )], "bra" -> TemplateBox[{"\[Placeholder]"}, "Bra", DisplayFunction -> (RowBox[{"\[LeftAngleBracket]", #, "\[RightBracketingBar]"}]& )], "braket" -> TemplateBox[{"\[Placeholder]", "\[Placeholder]"}, "BraKet", DisplayFunction -> (RowBox[{"\[LeftAngleBracket]", #, "\[VerticalSeparator]", #2, "\[RightAngleBracket]"}]& )], "notation" -> RowBox[{"Notation", "[", RowBox[{TemplateBox[{"\[SelectionPlaceholder]"}, "NotationTemplateTag"], " ", "\[DoubleLongLeftRightArrow]", " ", TemplateBox[{"\[Placeholder]"}, "NotationTemplateTag"]}], "]"}], "notation>" -> RowBox[{"Notation", "[", RowBox[{TemplateBox[{"\[SelectionPlaceholder]"}, "NotationTemplateTag"], " ", "\[DoubleLongRightArrow]", " ", TemplateBox[{"\[Placeholder]"}, "NotationTemplateTag"]}], "]"}], "notation<" -> RowBox[{"Notation", "[", RowBox[{TemplateBox[{"\[SelectionPlaceholder]"}, "NotationTemplateTag"], " ", "\[DoubleLongLeftArrow]", " ", TemplateBox[{"\[Placeholder]"}, "NotationTemplateTag"]}], "]"}], "symb" -> RowBox[{"Symbolize", "[", TemplateBox[{"\[SelectionPlaceholder]"}, "NotationTemplateTag"], "]"}], "infixnotation" -> RowBox[{"InfixNotation", "[", RowBox[{TemplateBox[{"\[SelectionPlaceholder]"}, "NotationTemplateTag"], ",", "\[Placeholder]"}], "]"}], "addia" -> RowBox[{"AddInputAlias", "[", RowBox[{"\"\[SelectionPlaceholder]\"", "\[Rule]", TemplateBox[{"\[Placeholder]"}, "NotationTemplateTag"]}], "]"}], "pattwraper" -> TemplateBox[{"\[SelectionPlaceholder]"}, "NotationPatternTag"], "madeboxeswraper" -> TemplateBox[{"\[SelectionPlaceholder]"}, "NotationMadeBoxesTag"]},
TrackCellChangeTimes->False,
CellChangeTimeMergeInterval->3600,
ShowCursorTracker->False,
ShowPredictiveInterface->False,
DragAndDrop->False,
AutoStyleOptions->{"EmphasizedSyntaxErrorStyle"->{FontColor -> RGBColor[0.8, 0., 0.], Background -> RGBColor[1., 0.88, 0.51]},
"FunctionLocalVariableStyle"->{FontColor -> RGBColor[0.25098039215686274`, 0.5019607843137255, 0.]},
"LocalVariableStyle"->{FontColor -> RGBColor[1., 0.5019607843137255, 0.]},
"OrderOfEvaluationConflictStyle"->{FontColor -> RGBColor[0.8, 0.2, 0.]},
"PatternVariableStyle"->{FontColor -> RGBColor[0.5019607843137255, 0., 1.], FontSlant -> "Plain"},
"SymbolShadowingStyle"->{FontColor -> RGBColor[0.8, 0., 0.]},
"UndefinedSymbolStyle"->{FontColor -> RGBColor[0., 0.5019607843137255, 1.]}},
CodeAssistOptions->{"AutoPopupEnable"->False,
"FloatingElementEnable"->False,
"HeadHighlightStyle"->{Background -> RGBColor[0.8, 1., 0.4]},
"MatchHighlightStyle"->{Background -> RGBColor[1., 0.8, 0.4]}},
AutoItalicWords->{"Artlandia", "AuthorTools", "CalculationCenter", "Combinatorica", "DatabaseLink", "Geometrica", "Graphica", "GUIKit", "J/Link", "Magnetica", "Mathematica", "MathematicaMark", "MathGroup", "MathLink", "MathLM", "MathModelica", "MathOptimizer", "MathReader", "MathSource", "mathStatica", "MathTensor", "MATHwire", "MathWorld", "MonitorLM", "NET/Link", ".NET/Link", "Optica", "PrimeKit", "Publicon", "SchematicSolver", "ThreeScript", "VisualDSolve"},
SpellingOptions->{"AutoSpellCheckPopupDelay"->1000,
"MaxSuggestions"->50},
SpellingDictionaries->{"CorrectWords"->{"Abrikosov", "anticommute", "Anticommute", "anticommuting", "Anticommuting", "antisymmetrize", "Antisymmetrize", "anyons", "Anyons", "bilayer", "Bilayer", "bilinearity", "Bilinearity", "bipartition", "Bipartition", "Bogoliubov", "bosonic", "Bosonic", "brane", "Brane", "branes", "Branes", "cocycles", "Cocycles", "decohere", "Decohere", "Decoherent", "deconfine", "Deconfine", "deconfined", "Deconfined", "deconfinement", "Deconfinement", "dyon", "Dyon", "eigen", "Eigen", "eigenbasis", "Eigenbasis", "eigenenergies", "Eigenenergies", "eigenenergy", "Eigenenergy", "eigenspaces", "Eigenspaces", "Eq", "exponentiate", "Exponentiate", "extremization", "Extremization", "fermionic", "Fermionic", "Fierz", "fractionalization", "Fractionalization", "fractionalize", "Fractionalize", "fractionalized", "Fractionalized", "gapless", "Gapless", "gaplessness", "Gaplessness", "gaugable", "Gaugable", "gauge", "Gauge", "Higgsed", "Higgsing", "irrep", "Irrep", "Kagome", "ket", "Ket", "kets", "Kets", "Luttinger", "magnon", "Magnon", "Majorana", "orthogonalization", "Orthogonalization", "paramagnet", "Paramagnet", "partons", "Partons", "plaquette", "Plaquette", "plaquettes", "Plaquettes", "prefactors", "Prefactors", "premodular", "Premodular", "quantumly", "Quantumly", "quasiparticles", "Quasiparticles", "qubit", "Qubit", "qudit", "Qudit", "qudits", "Qudits", "qutrit", "Qutrit", "semion", "Semion", "Shastry", "Simons", "spinless", "Spinless", "spinon", "Spinon", "spinons", "Spinons", "spinor", "Spinor", "Stratonovich", "Subfigures", "sublattice", "Sublattice", "sublattices", "Sublattices", "superfluid", "Superfluid", "th", "Th", "thermalization", "Thermalization", "thermalized", "Thermalized", "tricritical", "Tricritical", "unkinked", "Unkinked", "vierbein", "Vierbein", "vison", "Vison", "visons", "Visons", "Wannier", "Wess", "Wyle", "Yizhuang", "Yukawa", "Zumino", "Hellmann", "Bosonization", "Antiferromagnet", "Neel", "Codifferential", "codifferential"},
"IncorrectWords"->{},
"Suggestions"->{}},
AutoNumberFormatting->True,
RenderingOptions->{"HardwareAntialiasingQuality"->1.}]
